### PR TITLE
Init App

### PR DESCRIPTION
**Pull request by stoe**

### CODE REVIEW

**Comment by stoe** [comment]
@swinton, found the code again I mentioned the other day.

Not sure what we can make of it.

**Review by swinton — COMMENTED** [review]
Haven't looked too closely at your code yet, but could we:

1. Generate the PDF
1. Store it on Box
1. Post a comment (to the PR?) containing the URL to the PDF?

Might become a bit noisy though :thinking:

**Comment by stoe** [comment]
> Store it on Box

@swinton, great plan of attack.

I had that 💡 a while back, but gave up as I didn't have a api.box.com API key to do that for GitHub's account. Do you know where we could get one?

Everything else basically works already.

**Comment by stoe** [comment]
https://www.npmjs.com/package/box-node-sdk for reference.

**Pull request closed without merging**
